/**
 * This script was generated by Loon to simulate http requests.
 */

let url = "https://tdx-live.tdx.com.cn/tdxzengcong/%E9%82%80%E8%AF%B7%E6%96%B0%E7%94%A8%E6%88%B7banner_1632472003505.png";
let headers = {
    'origin':'file://',
    'sec-fetch-dest':'image',
    'accept-language':'zh-SG,zh-CN;q=0.9,zh-Hans;q=0.8',
    'user-agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 supporttdxziphtml TdxIOS/1.00 iPhone17,2',
    'sec-fetch-site':'cross-site',
    'accept':'image/webp,image/avif,image/jxl,image/heic,image/heic-sequence,video/*;q=0.8,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5',
    'accept-encoding':'gzip, deflate, br',
    'sec-fetch-mode':'cors',
};

var params = {
    url:url,
    timeout:5000,
    headers:headers,
    alpn:'h2',
};

$httpClient.get(params, function(errormsg,response,data) {
    if (errormsg) {
        console.log(errormsg);
    } else {
        console.log("Response Status: " + response.status);
        console.log("Response Headers: " + JSON.stringify(response.headers));
        console.log("Response Body: " + data);
    }
    $done();
});
